In [1]:
import pickle
import numpy as np

In [2]:
# load encoders
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))

# load model
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [3]:
# Assume user input
# PClass / Sex / Age / SibSp / Parch / Fare / Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1, 7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [5]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\diwan\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_sex

array([[0., 1.]])

In [7]:
# here the warning says : “I don’t see feature names, but I remember them.”

In [8]:
test_input_embarked  = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [9]:
test_input_embarked

array([[0., 0., 1.]])

### “Here, we have to do all of this manually because we’re not using pipelines.”

In [10]:
test_input_age = test_input[:,2].reshape(1,1)

In [11]:
test_input_transformed = np.concatenate(
    (
        test_input[:, [0, 3, 4, 5]],  # Pclass, SibSp, Parch, Fare
        test_input_age,               # imputed Age
        test_input_sex,               # encoded Sex
        test_input_embarked            # encoded Embarked
    ),
    axis=1
)

In [12]:
test_input_transformed.shape

(1, 10)

In [13]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

##### “Without pipelines, preprocessing becomes messy, repetitive, and error-prone.”